steps:
  # Install dependencies
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['install']

  # Build the application
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['run', 'build']

artifacts:
  objects:
    location: 'gs://tensure-apprenticeship-bucket-test/'
    paths: ['dist/']
serviceAccount: '431396521218@cloudbuild.gserviceaccount.com'
options:
  logging: CLOUD_LOGGING_ONLY