steps:
  # Install dependencies
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['install']

  # Build the application
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['run', 'build']

  # List the contents of the dist directory
  - name: 'ubuntu' # Or any image with ls
    entrypoint: 'bash'
    args: ['-c', 'ls -R dist/'] #Recursive listing
  # # Upload to Cloud Storage
  # - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  #   entrypoint: 'gsutil'
  #   args: ['-m', 'rsync', '-r', '-d', 'dist/', 'gs://tensure-apprenticeship-bucket-test/']

  # # Optionally invalidate CDN cache if you're using Cloud CDN
  # - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  #   entrypoint: 'gcloud'
  #   args: ['compute', 'url-maps', 'invalidate-cdn-cache', 'watering-app-load-balancer', '--path', '/*']

artifacts:
  objects:
    location: 'gs://tensure-apprenticeship-bucket-test/'
    paths: ['dist/**/*']
serviceAccount: '431396521218@cloudbuild.gserviceaccount.com'
options:
  logging: CLOUD_LOGGING_ONLY